repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: (observability|testing/tavern)
      - id: debug-statements
        exclude: tests/
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  - repo: https://github.com/ambv/black
    rev: 23.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config, src/setup.cfg]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          '--profile',
          'black',
          '--src-path',
          'src',
        ]
